name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 패키지 설치
        run: |
          pip install pygame openpyxl pyinstaller

      - name: EXE 빌드
        run: |
          pyinstaller SNU_Baseball_Manager_win.spec

      - name: 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: SNU-Baseball-Manager-Windows
          path: "dist/SNU Baseball Manager/"
